---
- name: "Create the {{ vg_name }} Volume Group."
  lvg:
    vg: "{{ vg_name }}"
    pvs: "/dev/{{ raw_disks }}"
    force: no
    state: present

- name: "Create the {{ lv_name }} Logical Volume."
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: "{{ require_lv_size }}"
    shrink: no
    active: yes
    force: no
    state: present

- name: "Create a {{ fs }} filesystem on lvm /dev/{{ vg_name }}/{{ lv_name }}."
  filesystem:
    fstype: "{{ fs }}"
    dev: "/dev/{{ vg_name }}/{{ lv_name }}"
    force: no

- name: "Create a directory to mount the filesystem."
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'

- name: "Mount the created {{ fs }} filesystem."
  mount:
    path: "{{ mount_point }}"
    src: "/dev/{{ vg_name }}/{{ lv_name }}"
    fstype: "{{ fs }}"
    opts: "defaults,nofail"
    state: "mounted"
